version: "2"
services:
  web:
    image: sslsite
    ports:
      - "8082:80"
    extra_hosts:
          - debug.dockerhost:${HOST_IP}
    volumes: # mount real sources for development
      - ./composer.lock:/var/www/composer.lock
      - ./composer.json:/var/www/composer.json
      - ./cron:/var/www/cron:delegated
      - ./src:/var/www/src
      - ./public:/var/www/public
      - ./config:/var/www/config
